version: '2'

services:
  frontend:
    build: tax-form-generator-web
    ports:
      - "4200:4200"

  backend:
    image: backend
    build: tax-form-generator-api
    ports:
      - "5000:5000"
    depends_on:
      - database
    links:
      - database

  database:
    image: postgres:9.6.12
    ports:
      - "5432:5432"

  migrations:
    image: backend
    entrypoint: ["dotnet", "ef", "database", "update"]
    depends_on:
      - database
    links:
      - database