version: '2'

services:
  frontend:
    image: r.cfcr.io/jbojcic1/tax-form-generator:docker-2
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: r.cfcr.io/jbojcic1/tax-form-generator-api:docker-2
  migrations:
    image: r.cfcr.io/jbojcic1/tax-form-generator-api-migrations:docker-2
